[package]
name = "minikv"
version = "0.1.0"
authors = ["Shoyo Inokuchi <shoyoinokuchi@gmail.com>"]
edition = "2018"

[lib]
name = "minikv"
path = "src/lib.rs"

[[bin]]
name = "minikv-server"
path = "src/bin.rs"

[dependencies]
